			<script type="text/javascript"
		      src="http://maps.googleapis.com/maps/api/js?key=<?echo Mage::getStoreConfig('youmaps/youmaps_group/youmaps_apikey',Mage::app()->getStore())?>&sensor=false">
		    </script>
		        <script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"
     		 type="text/javascript"></script>
<?php
echo $_GET["q"];
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
		        $addr = urlencode($_GET["q"]);
	        $url = 'http://maps.googleapis.com/maps/api/geocode/json?address='.$addr.'&sensor=false';
			$ch = curl_init();
	
			    curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
			    curl_setopt($ch, CURLOPT_HEADER, 0);
			    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			    curl_setopt($ch, CURLOPT_URL, $url);
			    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);       
			
			    $data = curl_exec($ch);
			    curl_close($ch);
	        $records = json_decode($data,true);
			$myLct = $records['results'][0]['geometry']['location']['lat'].', '.$records['results'][0]['geometry']['location']['lng'];
			$lat1 = $records['results'][0]['geometry']['location']['lat'];
			$lon1 = $records['results'][0]['geometry']['location']['lng'];
			$resource = Mage::getSingleton('core/resource');
		    $readConnection = $resource->getConnection('core_read');
		    $query = 'SELECT attribute_code FROM eav_attribute WHERE frontend_input="youmap"';
		    $results = $readConnection->fetchAll($query);
			$collection = Mage::getModel('catalog/product')->getCollection();
			$collection->addAttributeToSelect('name'); 
			$items=array();
			foreach ($results as $att){
				$collection->addAttributeToSelect($att);
			}
			foreach($collection AS $product){
				foreach ($results as $att) {
					     
					$att= $att['attribute_code'];
					$value=$product->getData();
					$tmp=explode('/',$value[$att]);
					$latlng=$tmp[0];
					$latlng=explode(',',trim($latlng,' '));
					$lat2 = $latlng[0];
					$lon2= $latlng[1];
					$distance = (3958*3.1415926*sqrt(($lat2-$lat1)*($lat2-$lat1) + cos($lat2/57.29578)*cos($lat1/57.29578)*($lon2-$lon1)*($lon2-$lon1))/180);
					$rndDst = round($distance, 3);
					$rndDst = (string) $rndDst;
					$items[$rndDst]=$product;
				}
			}
			ksort($items);
			?>
			<div class="category-products">
			<?php echo $this->getToolbarHtml() ?>
			<?php
			$_collectionSize = count($items);
			$_columnCount = $this->getColumnCount(); ?>
			<ul class="products-grid">
			<?
			foreach($items AS $_product){
				?>
				 <?php if ($i++%$_columnCount==0): ?>
			
			        <?php endif ?>
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
				<?php
			}
?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        </ul>
        </div>

<style type="text/css">
				#map_container { height:300px; width:400px;margin:0;}
				
			</style>
			<div id="map_container"><div id="map_canvas" style="width:400px;height:300px;"></div></div>
		    <script type="text/javascript">
			var map;
			var myLatlng = new google.maps.LatLng(<?php echo $myLct; ?>);
			function initialize() {
			  var mapOptions = {
			    zoom: 16,
			    center: new google.maps.LatLng(<?php echo $myLct; ?>),
			    mapTypeId: google.maps.MapTypeId.ROADMAP
			  };
			
			  map = new google.maps.Map(document.getElementById("map_canvas"),
			      mapOptions);
			    getMarkers();
				} 
			
	</script>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <p> IGNORE THESE:</p>
    <?php $markers= '<script type="text/javascript">
    				function getMarkers(){';
    	?>
    <script type="text/javascript">
    	function addMarker(location,title) {
        marker = new google.maps.Marker({
            position: location,
            map: map,
            title: title
        });
    }	</script>
    <?php $i=0; foreach ($_productCollection as $_product): ?>

    
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
        
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <?php
$attributes = Mage::getResourceModel('eav/entity_attribute_collection');
foreach($attributes AS $attribute){
	if($attribute->getFrontendInput()=='youmap'){
		$attr=$attribute->getAttributeCode();
		$value=$_product->getData();
		$tmp=explode('/',$value[$attr]);
		$latlng=$tmp[0];
		$name = mt_rand();
		?>
		<script type="text/javascript">
			var markerlct<?php echo $name; ?>=new google.maps.LatLng(<?php echo $latlng; ?>);

			var title<?php echo $name; ?>='<?php echo $_product->getName();?>';
		</script>
		<?php 
		$markers.= 'addMarker(markerlct'.$name.', title'.$name.' );';
	}
} ?>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <?php $markers.= '}</script>';
        echo $markers;?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);
        		google.maps.event.addDomListener(window, "load", initialize);</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
