<style>
.demo {
	-moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	background-color:#79bbff;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #84bbf3;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528ecc;
}.demo:hover {
	background-color:#378de5;
}.demo:active {
	position:relative;
	top:1px;
}


</style>
<div id="button-container" >
        <a class="demo" href='<?php echo $this->getUrl().'supportsuite/adminhtml_ticket'; ?>' id="button">Read my messages</a>
		<a class="demo" href='<?php echo $this->getUrl().'admin/catalog_product/new'; ?>' id="button">Add new product</a>
		<a class="demo" href='<?php echo $this->getUrl().'admin/catalog_product/'; ?>' id="button">My product list</a>
    </div>
<?php 

?>